-- creates database my_school and table in that database on MySQL server
-- for states: id is an int unique autogenerated and cant be null and is a primary key, name is varchar(256) and cant be null
-- if the database already exists, script should not fail
-- if table states already exists, script should not 

CREATE DATABASE IF NOT EXISTS my_school;
CREATE TABLE IF NOT EXISTS my_school.states_2 (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(256) NOT NULL);
